# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AroundAI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AroundAI
	pod 'GoogleMaps'
  	pod 'GooglePlaces'
	pod 'Firebase/Core'
    pod 'GooglePlacePicker'


  target 'AroundAITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AroundAIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
